# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    # Setup node env
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
    
    - name: Generate Env file
      run: mkdir -p src/environments && echo "${{ secrets.FIREBASE_ENV }}" > src/environments/environment.ts && cp src/environments/environment.ts src/environments/environment.prod.ts

    - name: Build Web app
      run: npm ci && npm run build

    # Runs a set of commands using the runners shell
    - name: Deploy to Firebase
      run: ./node_modules/.bin/firebase deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
